export const SEED_JOBS = [
  {
    title: "Senior Frontend Engineer",
    company: "Stripe",
    logo: "S",
    salary: "₹18,00,000 - ₹24,00,000",
    skills: ["React", "TypeScript", "GraphQL", "Tailwind"],
    location: "San Francisco, CA (Remote)",
    workplace: "Remote",
    department: "Engineering",
    experience: "4+ Years",
    description:
      "Join Stripe's world-class frontend team to build payment UIs used by millions globally. You'll architect scalable React components and GraphQL integrations.",
    responsibilities: [
      "Build and maintain high-performance React applications",
      "Collaborate with design and backend teams",
      "Write clean, well-tested TypeScript code",
      "Mentor junior engineers",
    ],
    recruiter: {
      name: "Emily Chen",
      role: "Senior Engineering Recruiter",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150",
    },
    status: "approved",
    applicants: 128,
    postedTime: "2 days ago",
  },
  {
    title: "AI/ML Engineer",
    company: "Google DeepMind",
    logo: "G",
    salary: "₹28,00,000 - ₹40,00,000",
    skills: ["Python", "TensorFlow", "PyTorch", "LLMs"],
    location: "London, UK (Hybrid)",
    workplace: "Hybrid",
    department: "AI Research",
    experience: "5+ Years",
    description:
      "Shape the future of AI at DeepMind. Work on cutting-edge language models and reinforcement learning systems that push the boundaries of what's possible.",
    responsibilities: [
      "Research and implement novel ML architectures",
      "Train and fine-tune large language models",
      "Publish research findings",
      "Collaborate with world-leading AI researchers",
    ],
    recruiter: {
      name: "James Wilson",
      role: "AI Talent Lead",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150",
    },
    status: "approved",
    applicants: 342,
    postedTime: "1 week ago",
  },
  {
    title: "Product Designer",
    company: "Linear",
    logo: "L",
    salary: "₹14,00,000 - ₹20,00,000",
    skills: ["Figma", "UX Research", "Prototyping", "Design Systems"],
    location: "Remote",
    workplace: "Remote",
    department: "Design",
    experience: "3+ Years",
    description:
      "Design beautiful, intuitive interfaces for Linear's project management platform. Work closely with engineering to ship pixel-perfect features.",
    responsibilities: [
      "Design end-to-end product experiences",
      "Build and maintain design system components",
      "Conduct user research and usability testing",
      "Collaborate with product and engineering",
    ],
    recruiter: {
      name: "Sofia Park",
      role: "Design Recruiter",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
    },
    status: "approved",
    applicants: 89,
    postedTime: "3 days ago",
  },
  {
    title: "Backend Engineer — Infra",
    company: "Vercel",
    logo: "V",
    salary: "₹22,00,000 - ₹30,00,000",
    skills: ["Go", "Kubernetes", "AWS", "PostgreSQL"],
    location: "New York, NY (Hybrid)",
    workplace: "Hybrid",
    department: "Infrastructure",
    experience: "5+ Years",
    description:
      "Build the serverless infrastructure powering millions of deployments per day. Work on Edge Network, build pipelines, and distributed systems at massive scale.",
    responsibilities: [
      "Design and implement scalable backend systems",
      "Optimize performance for global edge network",
      "Build CI/CD pipelines and developer tooling",
      "On-call rotation for production systems",
    ],
    recruiter: {
      name: "Marcus Johnson",
      role: "Infrastructure Recruiter",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    },
    status: "approved",
    applicants: 215,
    postedTime: "5 days ago",
  },
  {
    title: "DevRel Engineer",
    company: "Supabase",
    logo: "SB",
    salary: "₹16,00,000 - ₹22,00,000",
    skills: ["Next.js", "PostgreSQL", "Technical Writing", "Public Speaking"],
    location: "Remote (Worldwide)",
    workplace: "Remote",
    department: "Developer Relations",
    experience: "3+ Years",
    description:
      "Be the bridge between Supabase and its global developer community. Create content, build sample apps, and speak at conferences worldwide.",
    responsibilities: [
      "Create technical tutorials and blog posts",
      "Build open-source demo projects",
      "Represent Supabase at conferences",
      "Gather developer feedback for product team",
    ],
    recruiter: {
      name: "Aisha Patel",
      role: "Community Recruiter",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150",
    },
    status: "approved",
    applicants: 67,
    postedTime: "1 day ago",
  },
  {
    title: "Full Stack Engineer",
    company: "Razorpay",
    logo: "R",
    salary: "₹20,00,000 - ₹28,00,000",
    skills: ["React", "Node.js", "Redis", "MongoDB"],
    location: "Bengaluru, India",
    workplace: "Hybrid",
    department: "Payments Engineering",
    experience: "3+ Years",
    description:
      "Build the payment infrastructure for India's fastest growing fintech. Own features end-to-end from DB schema to React UI.",
    responsibilities: [
      "Build full-stack payment features",
      "Design low-latency APIs for payment processing",
      "Ensure PCI compliance in implementation",
      "Collaborate with product, design and QA teams",
    ],
    recruiter: {
      name: "Priya Sharma",
      role: "Tech Recruiter",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    },
    status: "approved",
    applicants: 190,
    postedTime: "4 days ago",
  },
];
